---
- name: Clone open5gs-k8s repo
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: main
    update: yes
    force: yes

- name: Update NS variable in prepare-demo-oai.sh
  ansible.builtin.lineinfile:
    path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
    regexp: '^NS='
    line: "NS=\"{{ ran_ns }}\""
    backrefs: true

- name: Update RUN_MODE variable in prepare-demo-oai.sh
  ansible.builtin.lineinfile:
    path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
    regexp: '^RUN_MODE='
    line: "RUN_MODE=\"full\""
    backrefs: true

- name: Update HOST_GNB variable in prepare-demo-oai.sh
  ansible.builtin.lineinfile:
    path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
    regexp: '^HOST_GNB='
    line: "HOST_GNB=\"{{ ansible_hostname }}\""
    backrefs: true

- name: Update LOCAL_INTERFACE variable in prepare-demo-oai.sh
  ansible.builtin.lineinfile:
    path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
    regexp: '^LOCAL_INTERFACE='
    line: "LOCAL_INTERFACE=\"{{ nic_interface }}\""
    backrefs: true

# - name: Disable FLEXRIC in prepare-demo-oai.sh if using aw2s gnb image
#   ansible.builtin.lineinfile:
#     path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
#     regexp: '^FLEXRIC='
#     line: "FLEXRIC=false"
#     backrefs: true
#   when: rru in ['jaguar', 'panther']

- name: Run prepare-demo-oai.sh to pull & configure OAI RAN charts
  ansible.builtin.command: "{{ script_path }} -a -R {{ rru }} -F {{ conf }}"
  args:
    chdir: "{{ repo_dest }}/oai-ran"
  register: ran_script
  changed_when: "'OAI5G charts are now configured' in ran_script.stdout"

#- name: Install OAI FlexRIC chart using Helm
#  kubernetes.core.helm:
#    name: oai-flexric
#    chart_ref: "{{ charts_base }}/oai-5g-ran/oai-flexric"
#    release_namespace: "{{ ran_ns }}"
#    create_namespace: true
#    state: present
#    wait: true
#  register: helm_flex

#- name: Install OAI CORE chart using Helm
#  kubernetes.core.helm:
#    name: oai-
#    chart_ref: "{{ charts_base }}/oai-5g-ran/oai-gnb"
#    release_namespace: "{{ ran_ns }}"
#    create_namespace: true
#    state: present
#    wait: true
#  register: helm_gnb

- name: Wait for demo_oai.sh to exist
  ansible.builtin.wait_for:
    path: "{{ demo_oai_dir }}/demo_oai.sh"
    state: present
    timeout: 600
    delay: 2

- name: Stat demo_oai.sh
  ansible.builtin.stat:
    path: "{{ demo_oai_dir }}/demo_oai.sh"
  register: demo_oai_stat

- name: Fail if demo_oai.sh is missing (after wait)
  ansible.builtin.fail:
    msg: "demo_oai.sh not found in {{ demo_oai_dir }}. Check repo/branch or script name."
  when: not demo_oai_stat.stat.exists

- name: Ensure demo_oai.sh is executable
  ansible.builtin.file:
    path: "{{ demo_oai_dir }}/demo_oai.sh"
    mode: "0755"

- name: Run demo_oai.sh {{ demo_oai_cmd }}
  ansible.builtin.command: "./demo_oai.sh {{ demo_oai_cmd }}"
  args:
    chdir: "{{ demo_oai_dir }}"
  register: demo_oai_run
  changed_when: >
    demo_oai_run.rc == 0 and
    ('already running' not in (demo_oai_run.stdout | lower)) and
    ('already running' not in (demo_oai_run.stderr | lower))


# - name: Install OAI gNB chart using Helm
#   kubernetes.core.helm:
#     name: oai-gnb
#     chart_ref: "{{ charts_base }}/oai-5g-ran/oai-gnb"
#     release_namespace: "{{ ran_ns }}"
#     create_namespace: true
#     state: present
#     wait: true
#   register: helm_gnb
